import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar></Navbar>
         <div className="h-screen">
          {children}
          </div>
         <footer className="text-center text-4xl">
            this is my footer
         </footer>
        </body>
    </html>
  );
}
